fold_id: 4
data_root: "your dataset path"
save_root: "your save path"
max_epochs: 150
cuda_id: 1
# frequent of validation
val_interval: 1
batch_size: 4
num_workers: 0
learning_rate: 1e-3
weight_decay: 0
dice_weight: 0.5
bce_weight: 0.5
early_stop_patience: 20
lr_decay_epoch: 15
